### ISSUE TITLE
Some default values are not displaying in netconf client

### ISSUE THREAD

**Issue by Bharanidharan-S** [OpenClovis/OpenYuma#11]
Dear Team,

I am seeing some issues with default values to be shown in netconf client using get-with-default-->report-all. So please guide me where went wrong.

I could see default values of leaf parameters are displaying in netconf client using the option mentioned above. But not for all leafs, some of the leaf's default values are not shown.
I have given below information of netconf client and yang part of code which gives issues. Also see the capabilities info in the attachment
![capablities provisioned](https://cloud.githubusercontent.com/assets/13120192/9083798/e4106a76-3b8a-11e5-9272-c283df6e2633.PNG)
.

Kindly comment incase of any further information required.

Please find below details for your understanding:
=====================================
Netconf client:
 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
NETCONFc: Seguesoft NETCONFc 
Version: 2.0
=====================================

=====================================
Yang file 
 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
NOTE: < Leafs which are not displaying its default-values under the list "noise-margin-profile" and vectoring-profile mentioned below >:
 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

/* Noise Margin Profile. */
list noise-margin-profile {
	key name;
	description
			"A list of noise margin profiles.";

	leaf name {
			type string;
			description
					"A name that uniquely identifies the profile.";
	}
	
	container downstream {
		description
			"Downstream noise margin profile";
		
		container noise-margin {
			description
				"Noise margin parameters";

			leaf target-noise-margin {
				type uint16 {
					range "0..310" {
						description
							"Defines a range equivalent to 0 to 31 dB.";
						}
				}
				units "0.1 dB";
				default 60;
				description
					"Defines the  target noise margin for the Channel
					Initialization Policy.";
				reference
					"ITU-T G.997.2 clause 7.1.3.1 (TARSNRMds) and clause 7.1.3.2
					(TARSNRMus); ITU-T G.9701 clause 12.3.7.";
			}
			leaf maximum-noise-margin {
				type uint16 {
					range "0..310 | 511" {
						description
							"Defines a range equivalent to 0 to 31 dB.
							Special value 511: No maximum bound.";
					}
				}
				units "0.1 dB";
				default 511;
				description
					"Defines the maximum noise margin used in the Channel
					Initialization Policy.
					A special value, 511, indicates there is no maximum bound
					for the noise margin (i.e., the maximum noise margin is
					infinite).";
				reference
					"ITU-T G.997.2 clause 7.1.3.3 (MAXSNRMds) and clause 7.1.3.4
					(MAXSNRMus); ITU-T G.9701 clause 12.3.7.";
			}

			leaf minimum-noise-margin {
				type uint16 {
					range "0..310" {
						description
						"Defines a range equivalent to 0 to 31 dB.";
					}
				}
				units "0.1 dB";
				default 0;
				description
					"Defines the minimum noise margin the FTU receiver shall
					tolerate.  If the noise margin (SNRM) falls below this
					level, the FTU receiver requests the FTU transmitter to
					increase the FTU transmit power.  If an increase to FTU
					transmit power is not possible, a loss-of-margin(lom) defect
					occurs. Upon persistency of the lom defect, the FTU receiver
					triggers a re-initialization (see clause 12.1.4.2/G.9701).";
				reference
					"ITU-T G.997.2 clause 7.1.3.5 (MINSNRMds) and clause 7.1.3.6
					(MINSNRMus); ITU-T G.9701 clause 12.3.4.2.1.";
			}
		}
	}
}  /* list noise-margin-profile ends*/

/* Vectorng profile parameters. */
list vectoring-profile {
	key name;
	description
			"A list of vectoring profiles.";

	leaf name {
			type string;
			description
					"A name that uniquely identifies the profile.";
	}
	container downstream {
		description
				"Downstream vectoring parameters";
		leaf fext-cancel-enabled {
			type boolean;
			default true;
			description
				"Defines whether FEXT cancellation in the given direction
				from all the other vectored lines into the line in the
				vectored group is enabled or disabled.";
			reference
				"ITU-T G.997.2 clause 7.1.7.1 (FEXT_CANCEL_ENABLEds) and
				clause 7.1.7.2 (FEXT_CANCEL_ENABLEds); ITU-T G.9701 clause
				11.4.3.1.";
		}
	}
	container upstream {
		description
			"Upstream vectoring parameters";

		leaf fext-cancel-enabled {
			type boolean;
			default true;
			description
				"Defines whether FEXT cancellation in the given direction
				from all the other vectored lines into the line in the
				vectored group is enabled or disabled.";
			reference
				"ITU-T G.997.2 clause 7.1.7.1 (FEXT_CANCEL_ENABLEds) and
				clause 7.1.7.2 (FEXT_CANCEL_ENABLEds); ITU-T G.9701 clause
				11.4.3.1.";
		}
	}
}
=====================================

**Comment by hoangle** [comment]
Hi,
Please try running netconf server with param: --default-style=report-all to see any different.
Regards,
Hoang

**Comment by Bharanidharan-S** [comment]
Dear Hoang,

Thanks for your response.
Same behavior exists even after including --default-style=report-all. 
RPC request also triggered correctly.

For your information: (RPC reply and request - With no default-values in its reply..)

Request ########################################
<?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="3" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get>
    <filter type="subtree">
      <bbf-fast:configs xmlns:bbf-fast="urn:ietf:params:xml:ns:yang:bbf-fast-vop">
        <bbf-fast:profiles>
          <bbf-fast:noise-margin-profile/>
        </bbf-fast:profiles>
      </bbf-fast:configs>
    </filter>
    <with-defaults xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">report-all</with-defaults>
  </get>
</rpc>


Reply Ok or Operation Successful #####################
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3" last-modified="2015-08-06T05:40:06Z">
  <data>
    <configs xmlns="urn:ietf:params:xml:ns:yang:bbf-fast-vop">
      <profiles>
        <noise-margin-profile>
          <name>hi</name>
        </noise-margin-profile>
      </profiles>
    </configs>
  </data>
</rpc-reply>

**Comment by hoangle** [comment]
The param should also applied for netconfd too (via netconfd.conf or --default-style=report-all).
