### ISSUE TITLE
compile error happened.

### ISSUE THREAD

**Issue by JiangPingWang** [OpenClovis/OpenYuma#13]
root@vaio1:/home/ojumpin# cd ~
root@vaio1:~# ls
Desktop  openvnf  OpenYuma-master  pythonSrc
root@vaio1:~# cd Open
bash: cd: Open: 没有那个文件或目录
root@vaio1:~# cd OpenYuma-master/
root@vaio1:~/OpenYuma-master# make
for dir in  libtecla netconf libtoaster; do\
	  cd $dir && make && cd ..;\
        done
make[1]: 正在进入目录 `/root/OpenYuma-master/libtecla'
make[2]: 正在进入目录 `/root/OpenYuma-master/libtecla'
make[2]: 没有什么可以做的为 `default'。
make[2]:正在离开目录 `/root/OpenYuma-master/libtecla'
make[1]:正在离开目录 `/root/OpenYuma-master/libtecla'
make[1]: 正在进入目录 `/root/OpenYuma-master/netconf'
for dir in src modules etc doc man util; do\
	  cd $dir && make  all && cd ..;\
        done
make[2]: 正在进入目录 `/root/OpenYuma-master/netconf/src'
mkdir -p ../target
mkdir -p ../target/bin
mkdir -p ../target/lib
for dir in agt mgr ncx ydump subsys netconfd yangdump yangdiff yangcli; do\
	  mkdir -p ../target/$dir;\
	done
/bin/sh platform/setversion.sh
for dir in agt mgr ncx ydump subsys netconfd yangdump yangdiff yangcli; do\
	  cd $dir && make  all && cd ..;\
        done
make[3]: 正在进入目录 `/root/OpenYuma-master/netconf/src/agt'
gcc -DLINUX=1 -DGCC=1 -DDEBUG -DHAS_FLOAT=1 -Wall -Wno-long-long -Wformat-y2k -Winit-self -Wswitch-default -Wunused-parameter -Wextra -Wundef -Wshadow -Wpointer-arith -Wwrite-strings -Wbad-function-cast -Wcast-qual -Waggregate-return -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -Wpacked -Winvalid-pch -Wredundant-decls -Wnested-externs -Winline -std=gnu99  -fPIC -O2   \
         -I. -I../agt -I../mgr -I../ncx -I../platform -I../ydump -I/usr/include -I/usr/include/libxml2 -I/usr/include/libxml2/libxml   -c -o ../../target/agt/agt_acm.o agt_acm.c 
In file included from agt.h:119:0,
                 from agt_acm.c:79:
../ncx/help.h:35:23: fatal error: xmlstring.h: 没有那个文件或目录
 #include <xmlstring.h>
                       ^
compilation terminated.
make[3]: *** [../../target/agt/agt_acm.o] 错误 1
make[3]:正在离开目录 `/root/OpenYuma-master/netconf/src/agt'
/bin/sh: 2: cd: can't cd to mgr
/bin/sh: 2: cd: can't cd to ncx
/bin/sh: 2: cd: can't cd to ydump
/bin/sh: 2: cd: can't cd to subsys
/bin/sh: 2: cd: can't cd to netconfd
/bin/sh: 2: cd: can't cd to yangdump
/bin/sh: 2: cd: can't cd to yangdiff
/bin/sh: 2: cd: can't cd to yangcli
make[2]: *** [treeall] 错误 2
make[2]:正在离开目录 `/root/OpenYuma-master/netconf/src'
/bin/sh: 2: cd: can't cd to modules
/bin/sh: 2: cd: can't cd to etc
/bin/sh: 2: cd: can't cd to doc
/bin/sh: 2: cd: can't cd to man
/bin/sh: 2: cd: can't cd to util
make[1]: *** [treeall] 错误 2
make[1]:正在离开目录 `/root/OpenYuma-master/netconf'
/bin/sh: 2: cd: can't cd to libtoaster
make: *** [yuma-all] 错误 2
root@vaio1:~/OpenYuma-master# ^C
root@vaio1:~/OpenYuma-master# 

Hi! There was a broken while I compile it using make. Follow the reason I also cannot found the file "xmlstring.h" in my harddisk. How to solve the problem to continue for "make install" ? thank you!

**Comment by hoangle** [comment]
Hi,
The issue is libxml2 not being installed at your system and expected destination located in /usr/include/libxml2.

To install libxml2 on ubuntu: apt-get install libxml2 libxml2-dev

Regards,
Hoang

**Comment by JiangPingWang** [comment]
That's Ok, thank you! But another file "libssh2.h" also missing, SOS.


make[3]: 正在进入目录 `/root/OpenYuma-master/netconf/src/mgr'
gcc -DLINUX=1 -DGCC=1 -DDEBUG -DHAS_FLOAT=1 -Wall -Wno-long-long -Wformat-y2k -Winit-self -Wswitch-default -Wunused-parameter -Wextra -Wundef -Wshadow -Wpointer-arith -Wwrite-strings -Wbad-function-cast -Wcast-qual -Waggregate-return -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -Wpacked -Winvalid-pch -Wredundant-decls -Wnested-externs -Winline -std=gnu99  -fPIC -O2   \
         -I. -I../agt -I../mgr -I../ncx -I../platform -I../ydump -I/usr/include -I/usr/include/libxml2 -I/usr/include/libxml2/libxml   -c -o ../../target/mgr/mgr.o mgr.c 
mgr.c:32:22: **fatal error: libssh2.h**: 没有那个文件或目录
 #include  <libssh2.h>
                      ^
compilation terminated.
make[3]: *** [../../target/mgr/mgr.o] 错误 1

**Comment by hoangle** [comment]
$apt-get install libssh2-1 libssh2-1-dev

**Comment by JiangPingWang** [comment]
make && make install successed! Thanks very much.
