### ISSUE TITLE
Openyuma package compilation is broken

### ISSUE THREAD

**Issue by anukulverma** [OpenClovis/OpenYuma#16]
../../target/lib/libncx.so: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make[3]: *** [subsys] Error 1

========================================================
Needs to include -lrt option

**Comment by hoangle** [comment]
Hi,

Could you please give me full make command and log details with "make V=1"?

Thanks,
Hoang

**Comment by anukulverma** [comment]
Hi Hoang,

I used "make all" for compilation.

Find attached log for "make V=1", same error i got with "make all" also.

[make log.txt](https://github.com/OpenClovis/OpenYuma/files/140279/make.log.txt)

Regards,
Anukul

**Comment by hoangle** [comment]
Hi Anukul,

I see another error in make logs: 

> Makefile:78: dependencies: No such file or directory

Please give a try and let me know a result:
$cd /tmp/OpenYuma-master
$git pull
$make distclean
$make V=1

Regards,
Hoang

**Comment by anukulverma** [comment]
Find the logs

[make log.txt](https://github.com/OpenClovis/OpenYuma/files/140364/make.log.txt)

**Comment by hoangle** [comment]
At first glance:
fatal: Not a git repository (or any of the parent directories): .git

**Comment by gandrewstone** [comment]
You are right that function call is located in -lrt.  Thanks for the submission!  Weird that link was fine on Ubuntu Mint.  What Linux distro are you running?

**Comment by AndrewStoneOpenClovis** [comment]
You are right that function call is located in -lrt. Thanks for the submission! Weird that link was fine on Ubuntu Mint. What Linux distro are you running?

**Comment by anukulverma** [comment]
I am using fedora 17
