### ISSUE TITLE
Query on linking

### ISSUE THREAD

**Issue by harshawasthi90** [OpenClovis/OpenYuma#18]
My module depends on libcurl.
I compiled it registered it with server in configuration file, such that module is loaded on startup.

How can i link libcurl library..

**Comment by hoangle** [comment]
You can follow by example toaster's Makefile. Then, specified LD_LIBRARY_PATH must be exporting where libcurl located in before server running.

**Comment by harshawasthi90** [comment]
it worked..
Thanks...
