### ISSUE TITLE
Query regarding establish/destroy connection.

### ISSUE THREAD

**Issue by harshawasthi90** [OpenClovis/OpenYuma#19]
Hi,
I want to write some code for 2 scenarios.
-  Precisely just after server is started properly.
-  Precisely just after I press CTRL+ C, but just before server initiates a disconnect from clients. (Meaning my code should run before the server say bye to client.)

I tried to code it in `netconfd.c` but the problem for 2 scenarios is..

- If i insert startup code AFTER `res = agt_ncxserver_run();` then the previous line blocks the thread. and if i insert it before `res = agt_ncxserver_run();` then I cant be sure if the server has started properly.

- 

 If i insert the cleanup code static void netconfd_cleanup (void), then server has already terminated connection with the client.

Please help me on this.

**Comment by hoangle** [comment]
Adding customize code just before agt_ncxsever_run() is right approach.
If this code block the thread i.e loop forever, you have to create another thread.

W.r.t part 2, handle 2 signals as following:
void stopdaemon(int cookies)
{
/* Do your stuff */
......

}

signal(SIGTERM, stopdaemon);
signal(SIGINT, stopdaemon);
.....

**Comment by harshawasthi90** [comment]
Or can i put the code in...
`status_t  agt_ncxserver_run (void)` in `agt_ncxserver.c
`
- Startup code will be called just before the outermost while loop.
- Cleanup code will called just after the outermost while loop.

Would it be right approach too?
Especially for the 2nd part. Connection to client is terminated after the outermost while loop. Right?
