### ISSUE TITLE
Query on creation of custom STREAM.

### ISSUE THREAD

**Issue by harshawasthi90** [OpenClovis/OpenYuma#20]
Hi,
I want that when the server is starting, it creates an additional stream (STREAM1) on initialization.
I used `make_sil_dir` command to generated .c file, in which I want  the my notifications to be sent to STREAM1 and not default NETCONF stream.

I read the docs which say that only NETCONF stream is supported by YUMA.
Is it possible to add my custom stream?

Thanks.

**Comment by hoangle** [comment]
No, it could not. Only NETCONF stream allow for any in come new subscription and notification also send to exactly this stream.
