### ISSUE TITLE
Query on get/edit-config operation

### ISSUE THREAD

**Issue by Barathi07** [OpenClovis/OpenYuma#22]
Please tell me which yuma api should i use to do "get" operation / "edit-config" operation through code.
Do i need to create dummy session in my code to do "get" operation? Is there any sample for this. Pls suggest a solution.

**Comment by hoangle** [comment]
There 2 ways to retrieve/set a val value:

1. Direct linking with ncx, agt library and use val_find_child(...) (SIL code implementing)
2. Using any NETCONF client i.e yang_cli, ncclient (https://github.com/ncclient/ncclient)

I assume you are implementing via SIL code, then you can use '1' to get/set a value.
Hoang

**Comment by Barathi07** [comment]
Can i use *agt_ses* / *agt_connect* to establish and connect to a dummy session?

**Comment by hoangle** [comment]
Yes, in case you need to convert XML to val value.

**Comment by Barathi07** [comment]
Hi,
Am getting the following error, when i try to do "xget" operation in a dummy session.:
"'netconfd: obj.c:10536: obj_is_rpc: Assertion `obj && "obj is NULL"' failed."

Can u suggest a solution for this. 
Also, is thr any sample code for dummy session creation?

**Comment by hoangle** [comment]
I need to know these steps that you are implementing. 

To get an value of an object, you need to get obj template base on module name, object name:
1. mymodule = ncx_find_module(moduleName, revision)
2. myobj = obj_find_template(mymodule->datadefQ,  moduleName, objectName)

Then, filling the value if config of object is true (container, leaf, ....)

I don't have any example to illustrate using of ses_new_dummy_scb() but you can refer into src to get an overview.

**Comment by Barathi07** [comment]
Thanks Hoangle.Now am able to get data from running config using cfg_get_config_id().
