### ISSUE TITLE
Query on copy-config

### ISSUE THREAD

**Issue by Barathi07** [OpenClovis/OpenYuma#25]
Hi,
i want to copy the configuration data from running to startup datastore through code. I couldn't find any api's in yuma docs. 
Pls suggest me an api to use for the above mentioned scenario.

**Comment by hoangle** [comment]
'val_clone' and other APIs at val.h probably match your intention.

**Comment by Barathi07** [comment]
Thanks for the information.

**Comment by Barathi07** [comment]
we can use this api "agt_ncx_cfg_save()" to save the running config data to startup datatstore.
