### ISSUE TITLE
Reg database operations for tables and filelds

### ISSUE THREAD

**Issue by pathori** [OpenClovis/OpenYuma#27]
Can somebody explain how openYuma does database operations in the device. For example database need the table id and field id information to operate. So how this information is mapped between YANG list/leaf to table/field.

**Comment by hoangle** [comment]
Netconf uses an Extensible Markup Language (XML). To get knowledge mapping YANG <=> YIN (XML), refer to https://tools.ietf.org/html/rfc6241.

**Comment by pathori** [comment]
I mean to operate on database the table id and field is information is required, but the yang file only contains the schema name. so what method is used to map between schema name and the table in data base.?

**Comment by hoangle** [comment]
I think you need to do itself at user app callback since netconf store data as tree. So, there is NO mapping between YANG model and table in DBMS.
