### ISSUE TITLE
SIL callbacks not generated

### ISSUE THREAD

**Issue by Bharanidharan-S** [OpenClovis/OpenYuma#9]
Dear team,

Before going to the issue, please find the yang files defined below the explanation – I have given yang files and auto-generated ‘c’ file, listed below:
yang files             : bbf-fast.yang, bbf-fast-service-profiles.yang  &  bbf-fast-service-types.yang
supported yangs : bbf-fast-interfaces.yang  &  bbf-fast-types.yang
‘c’ file                   : bbf-fast.c

I am trying to get a SIL code generated with all the callbacks for list and leafs listed in submodules, which is defined in bbf-fast-service-profiles.yang  &  bbf-fast-service-types.yang. These submodules are included in bbf-fast.yang.

While generating SIL code using bbf-fast.yang(eg., make_sil_dir bbf-fast), I am getting only init functions(shown in bbf-fast.c), no callbacks for list and leaf generated.

Actually I need callbacks for list and leafs to get generated along with the init functions. Bit confused where went wrong and which is causing the issue in generating callbacks for list and leafs!

Thanks in advance for helping me to get out from this issue.

========================================================================
-------------------------------------------------------------------------------------------------------------------

:::: bbf-fast.yang ::::

module bbf-fast {
  namespace "urn:ietf:params:xml:ns:yang:bbf-fast-vop";
  prefix bbf-fast;

  include bbf-fast-service-profiles;
  include bbf-fast-service-types;

  organization
    "TBD";

  contact
    "TBD";

  description
    "An experimental YANG module supporting Vector of Profiles
    for FAST lines (G.FAST).";

  revision 2015-02-27 {
    description
      "Initial revision.";
    reference
      "TBD";
  }
}
-------------------------------------------------------------------------------------------------------------------
:::: bbf-fast-service-profiles.yang ::::

submodule bbf-fast-service-profiles {
  belongs-to bbf-fast {
    prefix bbf-fast;
  }

  include bbf-fast-types;
  include bbf-fast-service-types;
  include bbf-fast-interfaces;

  organization
    "TBD";

  contact
    "TBD";

  description
    "This module contains a collection of YANG definitions for
    managing G.FAST service profiles.";

  revision 2015-02-27 {
    description
      "Initial revision.";
    reference
      "TBD";
  }

  typedef downstream-data-rate-profile-ref {
    type leafref {
      path "/bbf-fast:configs/bbf-fast:profiles/"
          + "bbf-fast:downstream-data-rate-profile/"
          + "bbf-fast:name";
    }
    description
      "Used to reference an upstream data rate profile";
  }

  augment "/bbf-fast:configs/bbf-fast:profiles" {
    description
      "Data nodes for service-related configuration profiles.";

    list downstream-data-rate-profile {
      key name;
      description
        "A list of downstream data-rate profiles.";

      leaf name {
        type string;
        description
          "Uniquely identifies the profile.";
      }

      uses data-rate-profile;
    }
  }
}
-------------------------------------------------------------------------------------------------------------------
:::: bbf-fast-service-types.yang ::::

submodule bbf-fast-service-types {
  belongs-to bbf-fast {
    prefix bbf-fast;
  }

  organization
    "TBD";

  contact
    "TBD";

  description
    "This module contains a collection of service-related YANG
    data types and grouping definitions for the management of
    G.FAST.";

  revision 2015-02-27 {
    description
      "Initial revision.";
    reference
      "TBD";
  }

  typedef data-rate {
    type uint32;
    units "1000 bit/second";
    description
      "Data rate in kbps.";
  }

  grouping data-rate-parameters {
    description
      "Data rate configuration parameters.";
    reference
      "ITU-T G.997.2 clause 7.2.1.";

    leaf maximum-net-data-rate {
      type data-rate;
      default 4294967295;
      description
        "Defines the value of the maximum net data rate (see clause
        11.4.2.2/G.9701).";
      reference
        "ITU-T G.997.2 clause 7.2.1.1 (MAXNDR).";
    }
  }
  grouping data-rate-profile {
    description
      "Defines the parameters contained in a data rate profile.";

    uses data-rate-parameters;
  }
}
-------------------------------------------------------------------------------------------------------------------
:::: bbf-fast-types.yang ::::

submodule bbf-fast-types {
  belongs-to bbf-fast {
    prefix fast-vop;
  }

  organization
    "TBD";

  contact
    "TBD";

  description
    "This module contains a collection of YANG data types
    definitions for the management of G.FAST.";

  revision 2015-02-27 {
    description
      "Initial revision.";
    reference
      "TBD";
  }

  typedef channel-number {
    type uint32 {
      range "1..4";
    }
    description
      "A number uniquely identifying a bearer channel within the
      scope of an interface.";
  }

  typedef fast-profiles {
    type bits {
      bit g.9701-profile-106a {
      position 0;
      description
        "ITU-T G.9701 profile 106a";
      }
    }
    description
      "Identifies supported G.FAST profiles.";
    reference
      "ITU-T G.9701 clause 6.";
  }
}
-------------------------------------------------------------------------------------------------------------------
:::: bbf-fast-interfaces.yang ::::

submodule bbf-fast-interfaces {
  belongs-to bbf-fast {
    prefix fast-vop;
  }

  import ietf-interfaces {
    prefix if;
  }

  include bbf-fast-types;

  organization
    "TBD";

  contact
    "TBD";

  description
    "This module contains a collection of YANG definitions for
    managing G.FAST interfaces and augments
    ietf-interfaces.yang.";

  revision 2015-02-27 {
    description
      "Initial revision.";
    reference
      "TBD";
  }

  container configs {
    description
      "G.fast configuration";

    container vectors {
      description
        "Vectors of profiles";
    }
  }

  augment "/if:interfaces/if:interface" {
    description
      "Data nodes for the configuration of G.FAST lines.";

    container fast-line {
      description
        "Line configuration data for G.FAST interfaces.";
    }
  }
}
-------------------------------------------------------------------------------------------------------------------
:::::::::::  bbf-fast.c ::::::::::::

/* module static variables */
static ncx_module_t *bbf_fast_mod;

/* put your static variables here */

/********************************************************************
* FUNCTION y_bbf_fast_init_static_vars
*
* initialize module static variables
*
********************************************************************/
static void y_bbf_fast_init_static_vars (void)
{
    bbf_fast_mod = NULL;

    /* init your static variables here */

} /* y_bbf_fast_init_static_vars */

/********************************************************************
* FUNCTION y_bbf_fast_init
*
* initialize the bbf-fast server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
status_t y_bbf_fast_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;
    agt_profile_t *agt_profile = agt_get_profile();

    y_bbf_fast_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_bbf_fast_M_bbf_fast)) {
                    return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_bbf_fast_R_bbf_fast)) {
        return ERR_NCX_WRONG_VERSION;
    }
    res = ncxmod_load_module(
        y_bbf_fast_M_bbf_fast,
        y_bbf_fast_R_bbf_fast,
        &agt_profile->agt_savedevQ,
        &bbf_fast_mod);
    if (res != NO_ERR) {
        return res;
    }

    /* put your module initialization code here */

    return res;
} /* y_bbf_fast_init */

/********************************************************************
* FUNCTION y_bbf_fast_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
status_t y_bbf_fast_init2 (void)
{
    status_t res = NO_ERR;

    /* put your init2 code here */

    return res;
} /* y_bbf_fast_init2 */

/********************************************************************
* FUNCTION y_bbf_fast_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
void y_bbf_fast_cleanup (void)
{
    /* put your cleanup code here */

} /* y_bbf_fast_cleanup */

/* END bbf_fast.c */

-------------------------------------------------------------------------------------------------------------------
========================================================================

**Comment by hoangle** [comment]
Hi, 
Please put extra param "--unified=true" into yangdump command at the file make_sil_dir to solve your issue.

Example:
yangdump --unified=true format=yc indent=4 module=$mod output=y_$mod.c

Regards,
Hoang

**Comment by Babu-Subramani** [comment]
Hi Hoang,

Thank you very much for the response.

With this option "unified=true" for yangdump, we could able to see some callbacks generated for some lists (eg: downstream-data-rate-profile).

But, callbacks for containers defined by augmenting other modules are not generated.

From the above example,  bbf-fast-interfaces.yang imports ietf-interfaces.yang and it also defines a container augmenting  a list ("/if:interfaces/if:interface") from ietf-interfaces.yang.

container fast-line {
  description
    "Line configuration data for G.FAST interfaces.";
}

There is no callback generated for this container (fast-line) which is augmenting "/if:interfaces/if:interface".

Is ther any other option to be enabled for generating callbacks for nodes/lists augmenting lists from other modules?

Please help us.

Thanks,
Babu S

**Comment by hoangle** [comment]
Hmn, currently not support SIL codegen for uses and augment.

**Comment by Babu-Subramani** [comment]
Hi Hoang,

But, the SIL code is generated for uses and augment when its augmenting from a sub-module instead of module.

In the above example, "list downstream-data-rate-profile" augments "/bbf-fast:configs/bbf-fast:profiles" which is part of bbf-fast-interfaces.yang (which is a sub-module). We dont see issue here.

But, the SIL code is not generated if we augment a list from a module (ietf-interfaces.yang).

Are you saying that augment and uses are not completely supported by yangdump? If Yes, then its contradicting with the above results. 

Please help.

Thanks,
Babu

**Comment by hoangle** [comment]
Yes, you're right. But those 'uses' are resolved in local module. You can see more trace logs with params '--log-level=debug4 --log=output.log' at yangdump command.

**Comment by Bharanidharan-S** [comment]
Thanks hoangle.
